language: r
sudo: false
cache: packages

r:
  - release
  - devel

r_github_packages:
- statnet/statnet.common
- statnet/network
- statnet/networkDynamic
- statnet/ergm-private@dev
- statnet/ergm.multi-private@dev
- statnet/tergm-private@dev
- statnet/tergmLite-private@dev
- statnet/EpiModel@summary_statistics

warnings_are_errors: true

notifications:
  email:
    on_success: never
    on_failure: change
